# version = "Two"
use_try_shorthand = true
use_field_init_shorthand = true
max_width = 120
newline_style = "Unix"
merge_derives = true
# condense_wildcard_suffixes = true
edition = "2021"
# imports_granularity = "Crate"
